# Generated by Django 4.2.5 on 2025-05-25 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookfolder_bookbookmark'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='base_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_sources', to='books.book'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='reason',
            field=models.CharField(blank=True, choices=[('author', '같은 저자'), ('genre', '같은 장르')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommended_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_targets', to='books.book'),
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('base_book', 'recommended_book', 'reason')},
        ),
    ]
