# Generated by Django 4.2.5 on 2025-05-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
        migrations.AddField(
            model_name='category',
            name='aladin_category_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
