# Generated by Django 4.2.5 on 2025-05-27 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestbookentry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='guestbookentry',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guestbook_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guestbookentry',
            name='emoji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
