# Generated by Django 4.2.5 on 2025-05-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_post_book_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ai_image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
